/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.game;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class CurrentRoundResult extends javax.swing.JFrame {

    /**
     * Creates new form Round
     * @param move1
     */
    int i,rounds,rslt=0;
    static int a=0,b=0;
    public CurrentRoundResult(String move1,int round,int j) {
        initComponents();
        Color backgroundcolor=new Color(255,255,255);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
        i=j;
        rounds=round;
        Random r=new Random();
        int move2=r.nextInt(2);
        String yourpath="",computerpath="";
        String[] moves = {"Rock","Paper","Scissors"};
        yourpath=returnyourmovepath(move1);
        computerpath=returncomputermovepath(moves[move2]);
        ImageIcon youricon=new ImageIcon(yourpath);
        ImageIcon computericon=new ImageIcon(computerpath);
        yourmoveicon.setIcon(youricon);
        computermoveicon.setIcon(computericon);
        whowins(move1,moves[move2]);
        if(j>=round-1){
            if(a>b)
                rslt=1;
            else if(b>a)
                rslt=-1;
            a=0;
            b=0;
            nextroundbutton.setText("NEXT!");
        }
        
    }

    private CurrentRoundResult() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblyourscore = new javax.swing.JLabel();
        lblcompscore = new javax.swing.JLabel();
        pnlplayground = new javax.swing.JPanel();
        yourmoveicon = new javax.swing.JLabel();
        computermoveicon = new javax.swing.JLabel();
        VS = new javax.swing.JLabel();
        nextroundbutton = new javax.swing.JButton();
        quitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));

        lblyourscore.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblyourscore.setForeground(new java.awt.Color(0, 0, 51));
        lblyourscore.setText("YOUR SCORE:  0");

        lblcompscore.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblcompscore.setForeground(new java.awt.Color(0, 0, 51));
        lblcompscore.setText("COMPUTER'S SCORE: 0");

        pnlplayground.setBackground(new java.awt.Color(255, 255, 210));

        VS.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        VS.setForeground(new java.awt.Color(0, 0, 0));
        VS.setText("V/S");

        nextroundbutton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nextroundbutton.setForeground(new java.awt.Color(0, 0, 102));
        nextroundbutton.setText("NEXT ROUND!");
        nextroundbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextroundbuttonMouseClicked(evt);
            }
        });

        quitbutton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        quitbutton.setForeground(new java.awt.Color(0, 0, 102));
        quitbutton.setText("QUIT!");
        quitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlplaygroundLayout = new javax.swing.GroupLayout(pnlplayground);
        pnlplayground.setLayout(pnlplaygroundLayout);
        pnlplaygroundLayout.setHorizontalGroup(
            pnlplaygroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlplaygroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yourmoveicon, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(VS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(computermoveicon, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlplaygroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextroundbutton)
                .addGap(56, 56, 56)
                .addComponent(quitbutton)
                .addGap(53, 53, 53))
        );
        pnlplaygroundLayout.setVerticalGroup(
            pnlplaygroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlplaygroundLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlplaygroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlplaygroundLayout.createSequentialGroup()
                        .addGroup(pnlplaygroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(computermoveicon, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yourmoveicon, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlplaygroundLayout.createSequentialGroup()
                        .addComponent(VS)
                        .addGap(196, 196, 196)))
                .addGroup(pnlplaygroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextroundbutton)
                    .addComponent(quitbutton))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlplayground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblyourscore, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcompscore, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblyourscore, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcompscore, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlplayground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextroundbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextroundbuttonMouseClicked
        // TODO add your handling code here:
        if(i>=rounds-1)
        {
            dispose();
            Result rs=new Result(rslt);
        }
        else
        {
            dispose();
            SelectOption srr=new SelectOption(rounds,i+1);
        }
    }//GEN-LAST:event_nextroundbuttonMouseClicked

    private void quitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Exit e=new Exit();
    }//GEN-LAST:event_quitbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void whowins(String s1,String s2){
        if(s1.equals("Rock") && s2.equals("Scissors"))
            a++;
        if(s2.equals("Rock") && s1.equals("Scissors"))
            b++;
        if(s1.equals("Rock") && s2.equals("Paper"))
            b++;
        if(s2.equals("Rock") && s1.equals("Paper"))
            a++;
        if(s1.equals("Paper") && s2.equals("Scissors"))
            b++;
        if(s2.equals("Paper") && s1.equals("Scissors"))
            a++;
        lblyourscore.setText("YOUR SCORE: "+Integer.toString(a));
        lblcompscore.setText("COMPUTER'S SCORE: "+Integer.toString(b));
    }
    public String returnyourmovepath(String move1){
        String path="";
        if(move1.equals("Rock"))
            path="src\\com\\game\\Rock1.PNG";
        if(move1.equals("Paper"))
            path="src\\com\\game\\Paper1.PNG";
        if(move1.equals("Scissors"))
            path="src\\com\\game\\Scissors1.PNG";
        return path;
    }
    public String returncomputermovepath(String move2){
        String path="";
        if(move2.equals("Rock"))
            path="src\\com\\game\\Rock2.PNG";
        if(move2.equals("Paper"))
            path="src\\com\\game\\Paper2.PNG";
        if(move2.equals("Scissors"))
            path="src\\com\\game\\Scissors2.PNG";
        return path;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentRoundResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentRoundResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentRoundResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentRoundResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentRoundResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VS;
    private javax.swing.JLabel computermoveicon;
    private javax.swing.JLabel lblcompscore;
    private javax.swing.JLabel lblyourscore;
    private javax.swing.JButton nextroundbutton;
    private javax.swing.JPanel pnlplayground;
    private javax.swing.JButton quitbutton;
    private javax.swing.JLabel yourmoveicon;
    // End of variables declaration//GEN-END:variables
}
