/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.game;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class Rounds extends javax.swing.JFrame {

    /**
     * Creates new form Rounds
     */
    public Rounds() {
        initComponents();
        Color backgroundcolor=new Color(0,0,0);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblselectnumber = new javax.swing.JLabel();
        lblofrounds = new javax.swing.JLabel();
        cmbrounds = new javax.swing.JComboBox();
        goplaybutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Number Of Rounds");
        setLocation(new java.awt.Point(100, 100));

        lblselectnumber.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        lblselectnumber.setForeground(new java.awt.Color(0, 128, 128));
        lblselectnumber.setText("SELECT NUMBER");

        lblofrounds.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        lblofrounds.setForeground(new java.awt.Color(0, 128, 128));
        lblofrounds.setText("OF ROUNDS");

        cmbrounds.setBackground(new java.awt.Color(255, 255, 255));
        cmbrounds.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        cmbrounds.setForeground(new java.awt.Color(0, 128, 128));
        cmbrounds.setMaximumRowCount(5);
        cmbrounds.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cmbrounds.setBorder(new javax.swing.border.MatteBorder(null));

        goplaybutton.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        goplaybutton.setForeground(new java.awt.Color(0, 128, 128));
        goplaybutton.setText("PLAY!");
        goplaybutton.setBorder(new javax.swing.border.MatteBorder(null));
        goplaybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goplaybuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblofrounds)
                    .addComponent(lblselectnumber)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbrounds, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(goplaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblselectnumber)
                .addGap(18, 18, 18)
                .addComponent(lblofrounds)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbrounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goplaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goplaybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goplaybuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        int round=Integer.parseInt(String.valueOf(cmbrounds.getSelectedItem())),j=0;
        SelectOption so;
        so = new SelectOption(round,j);
    }//GEN-LAST:event_goplaybuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rounds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbrounds;
    private javax.swing.JButton goplaybutton;
    private javax.swing.JLabel lblofrounds;
    private javax.swing.JLabel lblselectnumber;
    // End of variables declaration//GEN-END:variables
}
