/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.game;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class SelectOption extends javax.swing.JFrame {

    /**
     * Creates new form SelectOption
     */String move;
     int rounds,j;
    public SelectOption(int NoOfRounds,int i) {
        initComponents();
        Color backgroundcolor=new Color(0,0,0);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
        lblround.setText("    ROUND: "+Integer.toString(i+1));
        if(i>=NoOfRounds){
            dispose();
        }
        rounds=NoOfRounds;
        j=i;
    }

    private SelectOption() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblselectmove = new javax.swing.JLabel();
        rockicon = new javax.swing.JLabel();
        scissorsicon = new javax.swing.JLabel();
        papericon = new javax.swing.JLabel();
        rockbutton = new javax.swing.JButton();
        paperbutton = new javax.swing.JButton();
        scissorsbutton = new javax.swing.JButton();
        lblround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));

        lblselectmove.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        lblselectmove.setForeground(new java.awt.Color(0, 128, 128));
        lblselectmove.setText("SELECT YOUR MOVE!");

        rockicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/game/Rock1.PNG"))); // NOI18N

        scissorsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/game/Scissors1.PNG"))); // NOI18N

        papericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/game/Paper1.PNG"))); // NOI18N

        rockbutton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        rockbutton.setForeground(new java.awt.Color(0, 128, 128));
        rockbutton.setText("ROCK");
        rockbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rockbuttonMouseClicked(evt);
            }
        });

        paperbutton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paperbutton.setForeground(new java.awt.Color(0, 128, 128));
        paperbutton.setText("PAPER");
        paperbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paperbuttonMouseClicked(evt);
            }
        });

        scissorsbutton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        scissorsbutton.setForeground(new java.awt.Color(0, 128, 128));
        scissorsbutton.setText("SCISSORS");
        scissorsbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scissorsbuttonMouseClicked(evt);
            }
        });

        lblround.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblround.setForeground(new java.awt.Color(0, 128, 128));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblselectmove))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paperbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rockicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(papericon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(rockbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scissorsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scissorsicon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblselectmove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lblround)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(papericon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scissorsicon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rockicon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scissorsbutton)
                    .addComponent(paperbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rockbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rockbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        move="Rock";
        everyround(move);
    }//GEN-LAST:event_rockbuttonMouseClicked

    private void paperbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paperbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        move="Paper";
        everyround(move);
    }//GEN-LAST:event_paperbuttonMouseClicked

    private void scissorsbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scissorsbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        move="Scissors";
        everyround(move);
    }//GEN-LAST:event_scissorsbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public void everyround(String move) 
    {
        CurrentRoundResult crr=new CurrentRoundResult(move,rounds,j);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblround;
    private javax.swing.JLabel lblselectmove;
    private javax.swing.JButton paperbutton;
    private javax.swing.JLabel papericon;
    private javax.swing.JButton rockbutton;
    private javax.swing.JLabel rockicon;
    private javax.swing.JButton scissorsbutton;
    private javax.swing.JLabel scissorsicon;
    // End of variables declaration//GEN-END:variables
}
